kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  selfLink: >-
    /apis/apiextensions.k8s.io/v1/customresourcedefinitions/serviceinstances.servicecatalog.k8s.io
  uid: 21c16636-4b80-4566-a78b-12f254b64bf1
  resourceVersion: '20552058'
  generation: 1
  creationTimestamp: '2020-12-15T15:41:32Z'
  labels:
    app.kubernetes.io/managed-by: Helm
    svcat: 'true'
  annotations:
    meta.helm.sh/release-name: catalog
    meta.helm.sh/release-namespace: catalog
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: apiextensions.k8s.io/v1beta1
      time: '2020-12-15T15:41:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
            'f:svcat': {}
        'f:spec':
          'f:additionalPrinterColumns': {}
          'f:conversion':
            .: {}
            'f:strategy': {}
          'f:group': {}
          'f:names':
            'f:categories': {}
            'f:kind': {}
            'f:listKind': {}
            'f:plural': {}
            'f:singular': {}
          'f:preserveUnknownFields': {}
          'f:scope': {}
          'f:subresources':
            .: {}
            'f:status': {}
          'f:version': {}
          'f:versions': {}
        'f:status':
          'f:storedVersions': {}
    - manager: kube-apiserver
      operation: Update
      apiVersion: apiextensions.k8s.io/v1
      time: '2020-12-15T15:41:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:acceptedNames':
            'f:categories': {}
            'f:kind': {}
            'f:listKind': {}
            'f:plural': {}
            'f:singular': {}
          'f:conditions': {}
spec:
  group: servicecatalog.k8s.io
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    listKind: ServiceInstanceList
    categories:
      - all
      - svcat
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Class
          type: string
          jsonPath: .status.userSpecifiedClassName
        - name: Plan
          type: string
          jsonPath: .status.userSpecifiedPlanName
        - name: Status
          type: string
          jsonPath: .status.lastConditionState
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
  preserveUnknownFields: true
status:
  conditions:
    - type: KubernetesAPIApprovalPolicyConformant
      status: 'False'
      lastTransitionTime: '2020-12-15T15:41:32Z'
      reason: MissingAnnotation
      message: >-
        protected groups must have approval annotation
        "api-approved.kubernetes.io", see
        https://github.com/kubernetes/enhancements/pull/1111
    - type: NamesAccepted
      status: 'True'
      lastTransitionTime: '2020-12-15T15:41:32Z'
      reason: NoConflicts
      message: no conflicts found
    - type: Established
      status: 'True'
      lastTransitionTime: '2020-12-15T15:41:37Z'
      reason: InitialNamesAccepted
      message: the initial names have been accepted
  acceptedNames:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    listKind: ServiceInstanceList
    categories:
      - all
      - svcat
  storedVersions:
    - v1beta1
