version: 2.1
orbs:
  #See documentation at https://circleci.com/developer/orbs/orb/banzaicloud/helm
  # This is a 3rd party circle ci orb (aka a plugin) that required the circle ci admin to opt-in in the security settings
  helm: banzaicloud/helm@0.0.8
workflows:
  helm-chart-lint:
    jobs:
      - helm/lint-chart:
          charts-dir: mysql-charts/p-mysql
          filters:
            tags:
              ignore: /.*/
      - unit-tests
jobs:
  unit-tests:
    docker:
    # From https://circleci.com/developer/orbs/orb/banzaicloud/helm
      - image: ghcr.io/banzaicloud/helm:0.0.8
    working_directory: ~/osb-2-helm-poc
    steps:
      - checkout
      - run:
          name: Run helm chart unit tests
          command: |
            #helm plugin install https://github.com/xchapter7x/hcunit/releases/latest/download/hcunit_plugin.tgz
            curl -LO https://github.com/xchapter7x/hcunit/releases/latest/download/hcunit_plugin.tgz
            # env | sort
            #Try to find out where $HELM_HOME is
            # find / -name "helm-push*"
            # pwd
            # ls -al /.helm/helm/plugins/
            mkdir /.helm/helm/plugins/hcunit_plugin
            tar xvfz hcunit_plugin.tgz --directory=/.helm/helm/plugins/hcunit_plugin
            # ls -alRt /.helm/helm/plugins/
            cd mysql-charts;./test.bash

