version: 2.1
orbs:
  #See documentation at https://circleci.com/developer/orbs/orb/banzaicloud/helm
  # This is a 3rd party circle ci orb (aka a plugin) that required the circle ci admin to opt-in in the security settings
  helm: banzaicloud/helm@0.0.8
workflows:
  helm-chart-lint:
    jobs:
      - generate-from-osb
      - helm/lint-chart:
          charts-dir: mysql-charts/p-mysql
          filters:
            tags:
              ignore: /.*/
#Unit tests are currently disabled blocked by https://github.com/xchapter7x/hcunit/issues/31
#      - unit-tests
jobs:
  generate-from-osb:
    docker:
    # From https://circleci.com/developer/orbs/orb/banzaicloud/helm
      - image: ghcr.io/banzaicloud/helm:0.0.8
    working_directory: ~/osb-2-helm-poc
    steps:
      - checkout
      - run:
          name: Generate Helm from OSB catalog
          command: |
            # TODO: try to cache this download in the docker image or in the workspace.
            ./install-build-prereqs.bash
            # Just checking for now that generation does not fail.
            # Packaging is likely to be different in the future
            ./generate-readme.bash
            ./generate-app-readme.bash
            ./generate-chart_yml.bash

  unit-tests:
    docker:
    # From https://circleci.com/developer/orbs/orb/banzaicloud/helm
      - image: ghcr.io/banzaicloud/helm:0.0.8
    working_directory: ~/osb-2-helm-poc
    steps:
      - checkout
      - run:
          name: Generate from OSB catalog
          command: |
            #Just checking for now that
            ./generate-readme.bash
            ./generate-chart_yml.bash
      - run:
          name: Run helm chart unit tests
          command: |
            #helm plugin install https://github.com/xchapter7x/hcunit/releases/latest/download/hcunit_plugin.tgz
            curl -LO https://github.com/xchapter7x/hcunit/releases/latest/download/hcunit_plugin.tgz
            # env | sort
            #Try to find out where $HELM_HOME is
            # find / -name "helm-push*"
            # pwd
            # ls -al /.helm/helm/plugins/
            mkdir /.helm/helm/plugins/hcunit_plugin
            tar xvfz hcunit_plugin.tgz --directory=/.helm/helm/plugins/hcunit_plugin
            # ls -alRt /.helm/helm/plugins/
            cd mysql-charts;./test.bash

